### ISSUE TITLE
[BUG] SEEN Configuration "Mail from", "Test Email" and others not configurable.

### ISSUE THREAD

**Issue by MatthiasScharl** [piaudonn/SecurityNotifications#40]
**Describe the bug**
After successfully deploying the solution via the ARM template it is not possible to set certain configuration options such as "Mail from, "Test Email", "Support Email", Support Phone" and "Admin Email".  The fields are greyed out / inactive / not editable.

<img width="853" alt="image" src="https://github.com/piaudonn/SecurityNotifications/assets/94482111/7e335b69-1626-4c42-a137-413084e1c623">

**Comment by piaudonn** [comment]
Hello @MatthiasScharl , was the [setup script](https://github.com/piaudonn/SecurityNotifications/tree/main/deploy#execute-setupps1-script) ran successfully after the ARM template deployment?

**Comment by MatthiasScharl** [comment]
Hello @piaudonn, I ran the deployment including the setup script again and it is working as expected. Very nice work !
